language: node_js
addons:
  firefox: 'latest'
  chrome: stable
node_js:
  - '12.16.2'

install:
  - npm ci

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
    - CXX=g++-4.8
  matrix:
    - CI_ACTION="npm run test:ci"
    - CI_ACTION="npm run build"
    - CI_ACTION="npm run lint"

cache:
  directories:
    - node_modules
